// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: service.proto

package bft

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OM_SendValue_FullMethodName = "/OM/SendValue"
)

// OMClient is the client API for OM service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OMClient interface {
	SendValue(ctx context.Context, in *Value, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type oMClient struct {
	cc grpc.ClientConnInterface
}

func NewOMClient(cc grpc.ClientConnInterface) OMClient {
	return &oMClient{cc}
}

func (c *oMClient) SendValue(ctx context.Context, in *Value, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, OM_SendValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OMServer is the server API for OM service.
// All implementations must embed UnimplementedOMServer
// for forward compatibility.
type OMServer interface {
	SendValue(context.Context, *Value) (*emptypb.Empty, error)
	mustEmbedUnimplementedOMServer()
}

// UnimplementedOMServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOMServer struct{}

func (UnimplementedOMServer) SendValue(context.Context, *Value) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendValue not implemented")
}
func (UnimplementedOMServer) mustEmbedUnimplementedOMServer() {}
func (UnimplementedOMServer) testEmbeddedByValue()            {}

// UnsafeOMServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OMServer will
// result in compilation errors.
type UnsafeOMServer interface {
	mustEmbedUnimplementedOMServer()
}

func RegisterOMServer(s grpc.ServiceRegistrar, srv OMServer) {
	// If the following call pancis, it indicates UnimplementedOMServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OM_ServiceDesc, srv)
}

func _OM_SendValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OMServer).SendValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OM_SendValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OMServer).SendValue(ctx, req.(*Value))
	}
	return interceptor(ctx, in, info, handler)
}

// OM_ServiceDesc is the grpc.ServiceDesc for OM service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OM_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "OM",
	HandlerType: (*OMServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendValue",
			Handler:    _OM_SendValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
