// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: service.proto

package stripe_clone

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StripeService_ClientLogin_FullMethodName  = "/services.common.genproto.comms.StripeService/ClientLogin"
	StripeService_BankRegister_FullMethodName = "/services.common.genproto.comms.StripeService/BankRegister"
	StripeService_CheckBalance_FullMethodName = "/services.common.genproto.comms.StripeService/CheckBalance"
)

// StripeServiceClient is the client API for StripeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// /////////////////////////
type StripeServiceClient interface {
	ClientLogin(ctx context.Context, in *ClientLoginRequest, opts ...grpc.CallOption) (*ClientSessionResponse, error)
	BankRegister(ctx context.Context, in *BankRegistrationRequest, opts ...grpc.CallOption) (*BankRegistrationResponse, error)
	CheckBalance(ctx context.Context, in *CheckBalanceRequest, opts ...grpc.CallOption) (*CheckBalanceResponse, error)
}

type stripeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStripeServiceClient(cc grpc.ClientConnInterface) StripeServiceClient {
	return &stripeServiceClient{cc}
}

func (c *stripeServiceClient) ClientLogin(ctx context.Context, in *ClientLoginRequest, opts ...grpc.CallOption) (*ClientSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientSessionResponse)
	err := c.cc.Invoke(ctx, StripeService_ClientLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stripeServiceClient) BankRegister(ctx context.Context, in *BankRegistrationRequest, opts ...grpc.CallOption) (*BankRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BankRegistrationResponse)
	err := c.cc.Invoke(ctx, StripeService_BankRegister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stripeServiceClient) CheckBalance(ctx context.Context, in *CheckBalanceRequest, opts ...grpc.CallOption) (*CheckBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckBalanceResponse)
	err := c.cc.Invoke(ctx, StripeService_CheckBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StripeServiceServer is the server API for StripeService service.
// All implementations must embed UnimplementedStripeServiceServer
// for forward compatibility.
//
// /////////////////////////
type StripeServiceServer interface {
	ClientLogin(context.Context, *ClientLoginRequest) (*ClientSessionResponse, error)
	BankRegister(context.Context, *BankRegistrationRequest) (*BankRegistrationResponse, error)
	CheckBalance(context.Context, *CheckBalanceRequest) (*CheckBalanceResponse, error)
	mustEmbedUnimplementedStripeServiceServer()
}

// UnimplementedStripeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStripeServiceServer struct{}

func (UnimplementedStripeServiceServer) ClientLogin(context.Context, *ClientLoginRequest) (*ClientSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientLogin not implemented")
}
func (UnimplementedStripeServiceServer) BankRegister(context.Context, *BankRegistrationRequest) (*BankRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BankRegister not implemented")
}
func (UnimplementedStripeServiceServer) CheckBalance(context.Context, *CheckBalanceRequest) (*CheckBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckBalance not implemented")
}
func (UnimplementedStripeServiceServer) mustEmbedUnimplementedStripeServiceServer() {}
func (UnimplementedStripeServiceServer) testEmbeddedByValue()                       {}

// UnsafeStripeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StripeServiceServer will
// result in compilation errors.
type UnsafeStripeServiceServer interface {
	mustEmbedUnimplementedStripeServiceServer()
}

func RegisterStripeServiceServer(s grpc.ServiceRegistrar, srv StripeServiceServer) {
	// If the following call pancis, it indicates UnimplementedStripeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StripeService_ServiceDesc, srv)
}

func _StripeService_ClientLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StripeServiceServer).ClientLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StripeService_ClientLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StripeServiceServer).ClientLogin(ctx, req.(*ClientLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StripeService_BankRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BankRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StripeServiceServer).BankRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StripeService_BankRegister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StripeServiceServer).BankRegister(ctx, req.(*BankRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StripeService_CheckBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StripeServiceServer).CheckBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StripeService_CheckBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StripeServiceServer).CheckBalance(ctx, req.(*CheckBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StripeService_ServiceDesc is the grpc.ServiceDesc for StripeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StripeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.common.genproto.comms.StripeService",
	HandlerType: (*StripeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClientLogin",
			Handler:    _StripeService_ClientLogin_Handler,
		},
		{
			MethodName: "BankRegister",
			Handler:    _StripeService_BankRegister_Handler,
		},
		{
			MethodName: "CheckBalance",
			Handler:    _StripeService_CheckBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

const (
	BankService_GetClientSession_FullMethodName = "/services.common.genproto.comms.BankService/GetClientSession"
	BankService_CheckBalance_FullMethodName     = "/services.common.genproto.comms.BankService/CheckBalance"
)

// BankServiceClient is the client API for BankService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// /////////////////////////
type BankServiceClient interface {
	GetClientSession(ctx context.Context, in *ClientLoginRequest, opts ...grpc.CallOption) (*ClientSessionResponse, error)
	CheckBalance(ctx context.Context, in *CheckBalanceRequest, opts ...grpc.CallOption) (*CheckBalanceResponse, error)
}

type bankServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBankServiceClient(cc grpc.ClientConnInterface) BankServiceClient {
	return &bankServiceClient{cc}
}

func (c *bankServiceClient) GetClientSession(ctx context.Context, in *ClientLoginRequest, opts ...grpc.CallOption) (*ClientSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientSessionResponse)
	err := c.cc.Invoke(ctx, BankService_GetClientSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) CheckBalance(ctx context.Context, in *CheckBalanceRequest, opts ...grpc.CallOption) (*CheckBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckBalanceResponse)
	err := c.cc.Invoke(ctx, BankService_CheckBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BankServiceServer is the server API for BankService service.
// All implementations must embed UnimplementedBankServiceServer
// for forward compatibility.
//
// /////////////////////////
type BankServiceServer interface {
	GetClientSession(context.Context, *ClientLoginRequest) (*ClientSessionResponse, error)
	CheckBalance(context.Context, *CheckBalanceRequest) (*CheckBalanceResponse, error)
	mustEmbedUnimplementedBankServiceServer()
}

// UnimplementedBankServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBankServiceServer struct{}

func (UnimplementedBankServiceServer) GetClientSession(context.Context, *ClientLoginRequest) (*ClientSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClientSession not implemented")
}
func (UnimplementedBankServiceServer) CheckBalance(context.Context, *CheckBalanceRequest) (*CheckBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckBalance not implemented")
}
func (UnimplementedBankServiceServer) mustEmbedUnimplementedBankServiceServer() {}
func (UnimplementedBankServiceServer) testEmbeddedByValue()                     {}

// UnsafeBankServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BankServiceServer will
// result in compilation errors.
type UnsafeBankServiceServer interface {
	mustEmbedUnimplementedBankServiceServer()
}

func RegisterBankServiceServer(s grpc.ServiceRegistrar, srv BankServiceServer) {
	// If the following call pancis, it indicates UnimplementedBankServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BankService_ServiceDesc, srv)
}

func _BankService_GetClientSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).GetClientSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankService_GetClientSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).GetClientSession(ctx, req.(*ClientLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_CheckBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).CheckBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankService_CheckBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).CheckBalance(ctx, req.(*CheckBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BankService_ServiceDesc is the grpc.ServiceDesc for BankService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BankService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.common.genproto.comms.BankService",
	HandlerType: (*BankServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClientSession",
			Handler:    _BankService_GetClientSession_Handler,
		},
		{
			MethodName: "CheckBalance",
			Handler:    _BankService_CheckBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
